development: &default
  <<: *default
  adapter: mysql2
  database: rails_base_development
  pool: 32
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test: &test
  <<: *default
  database: rails_base_test
